apiVersion: v1
kind: Service
metadata:
  name: btpaypro-api
  namespace: btpaypro
spec:
  type: ClusterIP
  selector:
    app: btpaypro-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
