apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: btpaypro
type: Opaque

stringData:
  SA_PASSWORD: "HedhaMonMotdePasseExtraExtra147!"
  CONNECTION_STRING: "Server=mssql,1433;Database=BTPayProDb;User ID=sa;Password=HedhaMonMotdePasseExtraExtra147!;TrustServerCertificate=True;MultipleActiveResultSets=True"
