apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: btpaypro
type: Opaque
data:
  # echo -n 'YourStrong!Passw0rd' | base64
  SA_PASSWORD: <BASE64_OF_YourStrong!Passw0rd>
  # echo -n 'Server=mssql,1433;Database=BTPayPro;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;' | base64
  CONNECTION_STRING: <BASE64_OF_CONNECTION_STRING>
